name: BigEndian

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  big-endian:
    runs-on: ubuntu-latest
    steps:
    - name: Get the qemu container
      run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - name: Run uname
      run: uname -a
    - name: Run tests on s390x/ubuntu
      run: docker run --rm s390x/ubuntu bash -c "apt update && apt install -y gcc g++ make git && git clone https://github.com/kmilo17pet/QuarkTS.git --recursive && cd QuarkTS && make test"
      
