name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
        
    - name: install arm-none-eabi-gcc
      uses: fiam/arm-none-eabi-gcc@v1
      with:
        release: '10-2020-q4'
    - name: check arm-none-eabi-gcc version
      run: arm-none-eabi-gcc -v        
    - name: make
      run: make
    - name: make test
      run: make test
 build_x86:
   runs-on: ubuntu-latest
    name: Validate latest tag
    steps:
      - name: Store GCC information in a file
        uses: paulproteus/ubuntu-18.04-x86@0.1
        with:
          command: gcc -v 2> output.txt
      - name: Read GCC information from a file, x86
        uses: paulproteus/ubuntu-18.04-x86@0.1
        with:
          command: make test

