name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
        
    - name: install arm-none-eabi-gcc
      uses: fiam/arm-none-eabi-gcc@v1
      with:
        release: '10-2020-q4'
    - name: check arm-none-eabi-gcc version
      run: arm-none-eabi-gcc -v        
    - name: make
      run: make
    - name: make test
      run: make test
  linting:
    name: cppcheck
    runs-on: ubuntu-latest
    steps:
      - name: c-linter
        uses: tonybaloney/cppcheck-action@master
