name: documentation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: create dirs
      run: ls -l        
    - name: create dirs
      run: mkdir docout
    - name: Doxygen Action
      uses: mattnotmitt/doxygen-action@v1.3.1
      with:
        working-directory: 'docout/'
        doxyfile-path: 'doc/Doxygen'
    - name: Deploy doc
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docout    
